tap "versenilvis/iris"
# Incredibly fast JavaScript runtime, bundler, test runner, and package manager
brew "bun"
# Play, record, convert, and stream select audio and video codecs
brew "ffmpeg"
# Command-line benchmarking tool
brew "hyperfine"
# Open-source, cross-platform JavaScript runtime environment
brew "node@24", link: true
# Fast, disk space efficient package manager
brew "pnpm"
# Program that allows you to count code, quickly
brew "tokei"
# A highly customizable, blazing fast and context-aware CLI autocomplete/navigation tool
brew "versenilvis/iris/iris", trusted: true
# Customise mouse behavior
cask "linearmouse"
vscode "azemoh.one-monokai"
vscode "azemoh.theme-onedark"
vscode "biomejs.biome"
vscode "bradlc.vscode-tailwindcss"
vscode "christian-kohler.npm-intellisense"
vscode "databricks.neon-local-connect"
vscode "donjayamanne.githistory"
vscode "donjayamanne.python-environment-manager"
vscode "donjayamanne.python-extension-pack"
vscode "dsznajder.es7-react-js-snippets"
vscode "dustypomerleau.rust-syntax"
vscode "ecmel.vscode-html-css"
vscode "eserozvataf.one-dark-pro-monokai-darker"
vscode "formulahendry.code-runner"
vscode "gimly81.fortran"
vscode "github.vscode-github-actions"
vscode "github.vscode-pull-request-github"
vscode "golang.go"
vscode "inferrinizzard.prettier-sql-vscode"
vscode "james-yu.latex-workshop"
vscode "jeff-hykin.better-cpp-syntax"
vscode "jock.svg"
vscode "kamikillerto.vscode-colorize"
vscode "kevinrose.vsc-python-indent"
vscode "mathematic.vscode-latex"
vscode "mechatroner.rainbow-csv"
vscode "motion.motion-vscode-extension"
vscode "ms-azuretools.vscode-containers"
vscode "ms-dotnettools.csdevkit"
vscode "ms-dotnettools.csharp"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-python.debugpy"
vscode "ms-python.isort"
vscode "ms-python.python"
vscode "ms-python.vscode-python-envs"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.cpp-devtools"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.cpptools-extension-pack"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vscode.live-server"
vscode "ms-vscode.makefile-tools"
vscode "ms-vscode.remote-explorer"
vscode "msyrus.go-doc"
vscode "nize.oklch-preview"
vscode "njpwerner.autodocstring"
vscode "ohziinteractivestudio.ohzi-vscode-glb-viewer"
vscode "oxc.oxc-vscode"
vscode "pkief.material-icon-theme"
vscode "premparihar.gotestexplorer"
vscode "prisma.prisma"
vscode "redhat.vscode-xml"
vscode "rust-lang.rust-analyzer"
vscode "tamasfe.even-better-toml"
vscode "tauri-apps.tauri-vscode"
vscode "twxs.cmake"
vscode "unifiedjs.vscode-mdx"
vscode "vadimcn.vscode-lldb"
vscode "visualstudiotoolsforunity.vstuc"
vscode "vitest.explorer"
vscode "voidzero.vite-plus-extension-pack"
vscode "waderyan.gitblame"
vscode "xabikos.javascriptsnippets"
vscode "xaver.clang-format"
vscode "yoavbls.pretty-ts-errors"
npm "corepack"
npm "portless"
